#!/bin/bash
# -*- mode: sh -*-
# https://stackoverflow.com/questions/9229333/how-to-get-overall-cpu-usage-e-g-57-on-linux

cpu=$(top -bn2 | grep "Cpu(s)" | \
    sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
    awk '{print 100 - $1}' )
cpu_usage=$(printf "$cpu" | tail -1)
printf "%02.0f%%" $cpu_usage
